config/routes.rb
Rails.application.routes.draw do
  resources :ripples, except: [:edit, :destroy]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/ripple.rb
class Ripple < ApplicationRecord
validates :name, :message, presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/ripples_controller.rb
class RipplesController < ApplicationController
  before_action :set_ripple, only: [:show]

  # GET /ripples
  # GET /ripples.json
  def index   
    session[:page_number] = params[:page_num].to_i 
    @current_page = session[:page_number]

    @id = params[:id].to_i
    @ripples = Ripple.all
    if ( @current_page == 4) then
      @id1 = @ripples.order("created_at DESC").last.id
      @id2 = @ripples.order("created_at DESC").last.id + 9
    elsif ( @current_page == 3)
      @id2 = @id + 10
      @id1 = @id + 1     
    elsif ( @current_page == 2)
      @id2 = @id - 1
      @id1 = @id - 10
    elsif ( @current_page == 1)
      @id1 = Ripple.last.id - 9
      @id2 = Ripple.last.id
    elsif ( @current_page == 0)
      @id1 = Ripple.last.id - 9
      @id2 = Ripple.last.id
    end
     @ripples = Ripple.order("created_at DESC").where(id: @id1..@id2)
  end

  # GET /ripples/1
  # GET /ripples/1.json
  def show
  end

  # GET /ripples/new
  def new
    @ripple = Ripple.new
  end

  # GET /ripples/1/edit
  def edit
  end

  # POST /ripples
  # POST /ripples.json
  def create
    @ripple = Ripple.new(ripple_params)
    respond_to do |format|
      if @ripple.save
        format.html { redirect_to action: "index" }
        format.json { render :show, status: :created, location: @ripple }
      else
        format.html { render :new }
        format.json { render json: @ripple.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ripples/1
  # PATCH/PUT /ripples/1.json
  def update
    respond_to do |format|
      if @ripple.update(ripple_params)
        format.html { redirect_to @ripple, notice: 'Ripple was successfully updated.' }
        format.json { render :show, status: :ok, location: @ripple }
      else
        format.html { render :edit }
        format.json { render json: @ripple.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ripples/1
  # DELETE /ripples/1.json
  def destroy
    @ripple.destroy
    respond_to do |format|
      format.html { redirect_to ripples_url, notice: 'Ripple was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ripple
      @ripple = Ripple.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ripple_params
      params.require(:ripple).permit(:name, :url, :message)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ripples_helper.rb
module RipplesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CONSCIOUS/mess</title>

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
     <link href="https://fonts.googleapis.com/css?family=Press+Start+2P|Quantico" rel="stylesheet"> 
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

<div class = wrapper>
 <header>
    <h1>CONSCIOUS/mess</h1>
    <h2>...a stream of anonymous online ramblings</h2>
 </header>
  <body>
    <%= yield %>
  </body>
</div>

</html>

app/views/ripples/_form.html.erb
<%= form_with(model: ripple, local: true) do |form| %>
  <% if ripple.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(ripple.errors.count, "error") %> prohibited this ripple from being saved:</h2>

      <ul>
      <% ripple.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label 'Your name or alias (required)' %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label 'A website, yours or otherwise (optional)' %>
    <%= form.text_field :url %>
  </div>

  <div class="field">
    <%= form.label 'Your message/note/quote/rant (required)' %>
    <%= form.text_area :message %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/ripples/edit.html.erb
<h1>Editing Ripple</h1>

<%= render 'form', ripple: @ripple %>

<%= link_to 'Show', @ripple %> |
<%= link_to 'Back', ripples_path %>

app/views/ripples/index.html.erb
<p id="notice"><%= notice %></p>
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Message</th>
      <th>Posted</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @ripples.each do |ripple| %>
      <tr>
	<% if(ripple.url.nil? || ripple.url.empty?) %>
            <td><%= ripple.name %></td>
	<% else %>
	    <td><%= link_to ripple.name, "http://#{ripple.url}" %></td>
	<% end %>
        <td><%= ripple.message[0..50].gsub(/\s\w+$/,'...') %></td>
	<td><%= ripple.created_at %></td>
        <td><%= link_to 'Show', ripple %></td>    
      </tr>
    <% end %>
  </tbody>
</table>
<br>

<%= link_to 'Newest', ripples_path(:page_num => 1) %> |
<%= link_to 'Previous 10 Ripples', ripples_path(:page_num => 2, :id => @ripples.ids.last) %> |
<%= link_to 'Next 10 Ripples', ripples_path(:page_num => 3, :id => @ripples.ids.first) %> |
<%= link_to 'Oldest', ripples_path(:page_num => 4) %> |
<%= link_to 'New Ripple', new_ripple_path %>

app/views/ripples/new.html.erb
<h1>Say What's On Your Mind</h1>

<%= render 'form', ripple: @ripple %>

<%= link_to 'Back', ripples_path %>

app/views/ripples/show.html.erb
<p id="notice"><%= notice %></p>

<div class = show_name>
<% if(@ripple.url.nil? || @ripple.url.empty?) %>
    <%= @ripple.name %>
<% else %>
    <%= link_to @ripple.name, "http://#{@ripple.url}" %>
<% end %> said...
</div>

<div class = show_message>
  <%= @ripple.message %>
</div>

<%= link_to 'Back', ripples_path %>